### ISSUE TITLE
pymarkdown\core.py", line 4 ModuleNotFoundError: No module named 'StringIO'

### ISSUE THREAD

**Issue by stevem995** [jackdewinter/pymarkdown#1292]
## Prerequisites

* [ ] Are you running the latest version of this application? Yes
* [ ] Have you checked the [Frequently Asked Questions](https://pymarkdown.readthedocs.io/en/latest/faq) document? Yes
* [ ] Have you simplified the bug report to the essential details? Yes
  * [ ] Do you have a distinct command line to report? Yes
  * [ ] Can you clearly state the configuration for this bug report?
  * [ ] Do you have a minimal document that highlights this bug?
  * [ ] Are any required files (configuration or Markdown document) attached to the issue?
* [ ] Did you perform a cursory search of other issues to look for related issues?

### Bug Type

* [ ] Assertion Failure
* [ ] Documentation
* [ ] Scan/Rule not working as expected
* [ ] Fix/Rule not working as expected
* [x ] Other
  [Other reason]

## Prerequisites

* [ ] Are you running the latest version of this application? Yes

* [ ] Have you checked the [Frequently Asked Questions](https://pymarkdown.readthedocs.io/en/latest/faq) document? Yes

* [ ] Have you simplified the bug report to the essential details? Yes
  * [ ] Do you have a distinct command line to report? Yes
  * [ ] Can you clearly state the configuration for this bug report? Yes
  * [ ] Do you have a minimal document that highlights this bug? Yes
  * [ ] Are any required files (configuration or Markdown document) attached to the issue? No
* [ ] Did you perform a cursory search of other issues to look for related issues? yes

## Bug Report

pymarkdown\core.py", line 4 ModuleNotFoundError: No module named 'StringIO'

### Bug Type

* [ ] Assertion Failure
* [ ] Documentation
* [ ] Scan/Rule not working as expected
* [ ] Fix/Rule not working as expected
* [x ] Other
  [Other reason]

### Description

Running pymarkdown fails on no module found StringIO.

python -m pymarkdown version
Traceback (most recent call last):
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\site-packages\pymarkdown\__init__.py", line 1, in <module>
    from .core import process
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\site-packages\pymarkdown\core.py", line 4, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'

The StringIO module has been renamed:
https://docs.python.org/3/whatsnew/3.0.html
PEP 3131: Non-ASCII letters are now allowed in identifiers. (However,
the standard library remains ASCII-only with the exception of
contributor names in comments.)

The StringIO and cStringIO modules are gone. Instead, import the io
module and use io.StringIO or io.BytesIO for text and data
respectively.

### Specifics

What operating system and version are you running into this behavior on?

Windows 10 om Git-bash.

What version are you seeing this behavior in? (Run `pip list` or `pipenv run pip list` and look for the entry beside `pymarkdownlnt`.)

python -m pip list | ag pymarkdown
pymarkdown         0.1.4
pymarkdownlint     0.3.1

Are there any extra steps that need to be taken before executing the application?

No

What is the command line you invoke to get this behavior?

[Assume that anything up to the first `pymarkdown` or `pymarkdownlnt` is already provided.]

python -m pymarkdown version
or run the scriptp
pymarkdown version

Are you using a configuration file? Either on the command line or one of the implicit configuration files? If so, attach that file to this issue.

No

What Markdown document causes this behavior to manifest?  Attach that file to this issue.

[Attach a minimal Markdown document that makes this behavior occur.]

### Actual Behavior

python -m pymarkdown version
Traceback (most recent call last):
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\site-packages\pymarkdown\__init__.py", line 1, in <module>
    from .core import process
  File "$HOME\.pyenv\pyenv-win\versions\3.9.9\lib\site-packages\pymarkdown\core.py", line 4, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'

### Expected Behavior

The program should work.

**Comment by jackdewinter** [comment]
Can you please confirm that [this](https://github.com/jackdewinter/pymarkdown) is the package you are talking about, not [this](https://github.com/mrocklin/pymarkdown) one?

**Comment by stevem995** [comment]
@jackdewinter, you are correct, I have installed the mrocklin package.

**Comment by stevem995** [comment]
If I uninstall he pymarkdown package and keep pymarkdownlint, I cannot run the command with just pymarkdown  as per the instructions. In addition, I cannot run the command using the module as the package cannot be run directly.

**Comment by jackdewinter** [comment]
tried this here, and you need to uninstall and then reinstall pymarkdownlint.  the old pymarkdown replaced the stub used to run pymarkdownlint.

please let me know if this does not work.

**Comment by stevem995** [comment]
Got it working. 
Uninstalled and reinstalled. 
NOTE: There is actually another package by another author named pymarkdownlint 
which is easy to mix up with the i character included. 

Thanks for the help on this. I can now see scans.

**Comment by jackdewinter** [comment]
closed
