### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'StringIO'

### ISSUE THREAD

**Issue by Freed-Wu** [jackdewinter/pymarkdown#26]
```shell
❯ pip3 install PyMarkdown
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting PyMarkdown
  Using cached pymarkdown-0.1.4-py3-none-any.whl
Requirement already satisfied: toolz in ./.local/lib/python3.9/site-packages (from PyMarkdown) (0.11.1)
Installing collected packages: PyMarkdown
Successfully installed PyMarkdown-0.1.4
❯ pymarkdown -h
Traceback (most recent call last):
  File "/home/wzy/.local/bin/pymarkdown", line 3, in <module>
    from pymarkdown import process
  File "/home/wzy/.local/lib/python3.9/site-packages/pymarkdown/__init__.py", line 1, in <module>
    from .core import process
  File "/home/wzy/.local/lib/python3.9/site-packages/pymarkdown/core.py", line 4, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by jackdewinter** [comment]
Can you try and reproduce this with version 0.8.0?  https://pypi.org/project/pymarkdownlnt/ should be showing that as the latest version.

**Comment by Freed-Wu** [comment]
Oh, the version I used is too old. Sorry!
