### ISSUE TITLE
broken version 0.9.10 available from pypi

### ISSUE THREAD

**Issue by finbaromahony** [jackdewinter/pymarkdown#662]
I was able to download and use `0.9.10` but it fails for the following reasons
- it installs `0.5.2` of `application-properties`
- it is attempting to use functionality `clear_property_map` that was introduced in `0.6.0`

Steps to reproduce
```
pipenv shell
pip install pymarkdownlnt
pymarkdown --config ./pymarkdown.cfg scan README.md

Traceback (most recent call last):
  File "xxx/.venv/bin/pymarkdown", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "xxx/.venv/lib/python3.11/site-packages/pymarkdown/__main__.py", line 13, in main
    PyMarkdownLint().main()
  File "xxx/.venv/lib/python3.11/site-packages/pymarkdown/main.py", line 459, in main
    args = self.__initialize_subsystems(direct_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx/.venv/lib/python3.11/site-packages/pymarkdown/main.py", line 440, in __initialize_subsystems
    self.__set_initial_state(args)
  File "xxx/.venv/lib/python3.11/site-packages/pymarkdown/main.py", line 334, in __set_initial_state
    self.__apply_configuration_layers(args)
  File "xxx/.venv/lib/python3.11/site-packages/pymarkdown/main.py", line 320, in __apply_configuration_layers
    ApplicationPropertiesJsonLoader.load_and_set(
TypeError: ApplicationPropertiesJsonLoader.load_and_set() got an unexpected keyword argument 'clear_property_map'
```

Ideally a mechanism should be put in place to prevent pre-release versions getting to pypi

The following is the output given when installing pymarkdownlnt
```
pip install pymarkdownlnt
Collecting pymarkdownlnt
  xxx/pymarkdownlnt-0.9.10-py3-none-any.whl (318 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.0/318.0 kB 807.9 kB/s eta 0:00:00
Collecting application-properties==0.5.2
  Using cached xxx/application_properties-0.5.2-py3-none-any.whl (9.7 kB)
Collecting Columnar==1.4.1
  Using cached xxx/Columnar-1.4.1-py3-none-any.whl (11 kB)
Collecting typing-extensions==4.4.0
  Using cached xxx/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Requirement already satisfied: toolz in ./.venv/lib/python3.11/site-packages (from Columnar==1.4.1->pymarkdownlnt) (0.12.0)
Requirement already satisfied: wcwidth in ./.venv/lib/python3.11/site-packages (from Columnar==1.4.1->pymarkdownlnt) (0.2.6)
Installing collected packages: typing-extensions, Columnar, application-properties, pymarkdownlnt
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
    Uninstalling typing_extensions-4.5.0:
      Successfully uninstalled typing_extensions-4.5.0
Successfully installed Columnar-1.4.1 application-properties-0.5.2 pymarkdownlnt-0.9.10 typing-extensions-4.4.0

```

**Comment by jackdewinter** [comment]
Actually, its even more embarrassing than that.  there was a gap in my release testing.  Fixing now.

**Comment by jackdewinter** [comment]
Published 0.9.11 to fix this and creating an issue to better test the releases.  I have 6 tests that I do on new releases, and that usually catches problems.  Specifically for changes regarding dependencies, I need to bolster those tests to ensure that the dependency functionality is being tested in those release tests.

**Comment by finbaromahony** [comment]
🙌

**Comment by jackdewinter** [comment]
everything looks good here, and adding some new release tests. how do things look there?

**Comment by finbaromahony** [comment]
Yup, looks stellar to me
